spring:
  application:
    name: monitor
  security:
    user:
      name: micro
      password: 123456
  boot:
    admin:
      discovery:
        ignored-services: ${spring.application.name}

server:
  port: 8081
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka/
